### ISSUE TITLE
Momento samples for Lambda environment

### ISSUE THREAD

**Issue by pchaganti** [momentohq/client-sdk-nodejs#398]
Are there any recent samples for using momento inside the Lambda environment.  Can someone point me to an example for Lambda?

thanks!

**Comment by eaddingtonwhite** [comment]
@pchaganti Thanks for reaching out and checking out Momento! Here are some example repos deployed to AWS Lambda that leverage momento's nodejs sdk:

This one uses CDK
https://github.com/momentohq/serverless-api-demo
 
This one uses serverless framework
https://github.com/momentohq/serverless-tutorial

This one is bit more complex uses SAM and models a simple game with leaderboard and chat that leverages websockets as well
https://github.com/momentohq/acorn-hunt

Im going to close this issue but also please feel free to join our discord and I can help you directly in there as well if have more questions!
https://discord.gg/pAhE6hrbnB
