### ISSUE TITLE
Wire up Configuration object in Web SDK CacheClient

### ISSUE THREAD

**Issue by pgautier404** [momentohq/client-sdk-nodejs#433]
The Configuration interface for the Web SDK CacheClient only supports `getLoggerFactory()` at the moment. We need to finish implementing the configuration system to support transport strategy, retry strategy, and middlewares. When that is done, we can migrate the `client-timeout.test.ts` tests in the `client-sdk-nodejs` package to the common integration tests and run them against both nodejs and web packages.

**Comment by cprice404** [comment]
We may start with just timeouts and not solve retry/middleware right away.
